
stages:
  - test
  - deploy

##########################
# Daily data pipeline
##########################

.meltano-extracts:
  image: python:3.8
  before_script:
  - apt-get update && apt-get install -y jq
  - cd data/
  - pip3 install meltano
  - meltano install
  - echo "Installing creds file from CI..." && cp $MELTANO_ENV_FILE .env

hub-metrics-prod:
  extends:
  - .meltano-extracts
  variables:
    STAGE: prod
    JOB_ID: HUB-METRICS-PROD
  stage: deploy
  only:
  - schedule
  needs: []
  script:
  - meltano --environment=userdev elt tap-google-analytics target-athena --job_id=ga_athena_$JOB_ID
  # - meltano --environment=userdev invoke dbt:run
  # - meltano --environment=userdev elt tap-athena-metrics target-yaml-metrics
  # - meltano --environment=userdev elt tap-athena-audit target-yaml-audit
  # - meltano invoke awscli s3 cp audit.yml s3://$S3_BUCKET/hub_metrics/
  # - meltano invoke awscli s3 cp metrics.yml s3://$S3_BUCKET/hub_metrics/
  - meltano --environment=userdev elt tap-google-analytics target-athena --job_id=ga_athena_$JOB_ID --dump=state > state.json
  artifacts:
    paths:
    - state.json
    when: always

test-hub-metrics:
  extends:
  - hub-metrics
  stage: test
  only: 
    refs:
      - merge_requests
