apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.efs.claim_name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi